spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.vfewoocjynrbgyrhlqwo
spring.datasource.password=369011111#AbB
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

